config/routes.rb
Rails.application.routes.draw do
  get 'search_analytics/index'
  post "/search_analytics", to: "search_analytics#create"
  
  resources :posts
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"

  resources :search_analytics, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    def index
        if params[:search].present?
          Search.record_query(params[:search])
          @posts = Post.where("title ILIKE ?", "%#{params[:search]}%")
        else
          @posts = Post.all
        end
      
        respond_to do |format|
          format.html
          format.json { render json: @posts }
        end
      end
end

app/models/search.rb
# app/models/search.rb
class Search < ApplicationRecord
  validates :query, presence: true

  def self.record_query(query)
    search = find_or_initialize_by(query: query)
    search.counter ||= 0
    search.counter += 1
    search.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = if params[:search].present?
               Post.where("title ILIKE ?", "%#{params[:search]}%")
             else
               Post.all
             end

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/search_analytics_controller.rb
# app/controllers/search_analytics_controller.rb
class SearchAnalyticsController < ApplicationController
  before_action :authenticate_user!

  def create
    Search.record_query(params[:query])
    head :ok
  end

  def index
    @searches = Search.order(counter: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_analytics_helper.rb
module SearchAnalyticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealtimeSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'application', 'devise' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card mb-3">
  <div class="card-header">
    <h3 class="card-title"><%= post.title %></h3>
  </div>
  <div class="card-body">
    <p class="card-text"><%= post.content %></p>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Search</title>
    <%= stylesheet_link_tag 'main' %>
  </head>
  <body>
    <div data-controller="search">
      <%= form_with url: '#', method: :get, class: 'search-form mb-3', local: true do |f| %>
        <div class="input-group">
          <%= label_tag :search, 'Search:', class: 'input-group-text' %>
          <%= f.text_field :search, data: { target: "search.input" }, class: 'form-control' %>
        </div>
      <% end %>

      <div data-target="search.results">
        <%= render @posts %>
      </div>

      <%= link_to 'Search Analytics', search_analytics_path, class: 'btn btn-primary mt-3' %>
    </div>
  </body>
</html>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/search_analytics/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Search Analytics</title>
    <%= stylesheet_link_tag 'analytics' %>
  </head>
  <body>
    <div class="container">
      <h1>Search Analytics</h1>

      <table class="table">
        <thead>
          <tr>
            <th>Search Query</th>
            <th>Counter</th>
          </tr>
        </thead>
        <tbody>
          <% @searches.each do |search| %>
            <tr>
              <td><%= search.query %></td>
              <td><%= search.counter %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <%= link_to 'Back', root_path, class: 'btn btn-secondary mt-3' %>
    </div>
  </body>
</html>